/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c QTestableDBusAdaptor -a QTestableDBusAdaptor.h:QTestableDBusAdaptor.cpp org.qTestable.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef QTESTABLEDBUSADAPTOR_H_1298384323
#define QTESTABLEDBUSADAPTOR_H_1298384323

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.qTestable
 */
class QTestableDBusAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.qTestable")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.qTestable\">\n"
"    <method name=\"Automate\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"request\"/>\n"
"      <arg direction=\"out\" type=\"s\" name=\"response\"/>\n"
"    </method>\n"
"    <method name=\"RegisteredClasses\">\n"
"      <arg direction=\"out\" type=\"as\" name=\"response\"/>\n"
"    </method>\n"
"    <method name=\"RegisteredObjects\">\n"
"      <arg direction=\"out\" type=\"as\" name=\"response\"/>\n"
"    </method>\n"
"    <method name=\"IsEnabled\">\n"
"      <arg direction=\"out\" type=\"b\" name=\"response\"/>\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    QTestableDBusAdaptor(QObject *parent);
    virtual ~QTestableDBusAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    QString Automate(const QString &request);
    bool IsEnabled();
    QStringList RegisteredClasses();
    QStringList RegisteredObjects();
Q_SIGNALS: // SIGNALS
};

#endif
